version: '3.8'

services:
  database:
    container_name: "baza"
    image: 'sektahub/pgvector'
    ports:
      - "5433:5432"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    # networks: 
      # sektanetwork:
        # ipv4_address: "172.24.0.3"
    environment: 
      POSTGRES_PASSWORD: "sektaadmin"
    # Custom command or entrypoint if needed
    #command: /docker-entrypoint-initdb.d/install-pgvector.sh
  mongodb:
    container_name: "mongo"
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "admin123"